name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test_shells:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: test/environment.yml
      - name: run tests
        shell: bash -l {0}
        run: |
          pip install -e .
          pytest test/
